# FUNDING.yml
# Funding configuration for this repository.
# This file is used by GitHub to display funding options on your repository's page.
# Each entry includes two usernames for the corresponding funding platform.

github: ["astra", "lumen"]
patreon: ["astra", "lumen"]
open_collective: ["astra", "lumen"]
ko_fi: ["astra", "lumen"]
tidelift: ["astra", "lumen"]
buymeacoffee: ["astra", "lumen"]
liberapay: ["astra", "lumen"]
paypal: ["astra", "lumen"]
flattr: ["astra", "lumen"]
